# CSS is divided into partials that are compiled into a singular dist/stylesheet.css
# Make sure that file is current

name: Publish the Legos Static Site

on: workflow_dispatch
    # TODO: uncomment. we don't want this running in Kamino's repo
    #release:
    #    types: [published]

jobs:
    publish-legos:
        runs-on: ubuntu-latest

        steps:
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Build and Publish
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              # TODO: update NAME to match project!
              run: |
                  npm install
                  npm run-script fractal-build
                  aws s3 sync static-lego-library/ s3://legos.NAME.magrathea.guide
